accounts/urls.py
from django.urls import path, include

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('accounts/', include('accounts.urls')),
]

blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('topics/', views.topics, name='topics'),
    path('topics/<slug:slug>/', views.topic, name='topic'),
    path('<slug:slug>/', views.entry_detail, name='entry_detail'),
    path('@<str:username>/blogs/', views.user_entries, name='user_entries'),
    path('new_blog/<slug:slug>/', views.new_entry, name='new_entry'),
    path('edit_blog/<slug:slug>/', views.edit_entry, name='edit_entry'),
    path('delete_blog/<slug:slug>/', views.delete_entry, name='delete_entry'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    name = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=50, unique=True)

    def __str__(self):
        return self.name

class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    text = models.TextField()
    slug = models.SlugField(max_length=100, unique=True)
    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    public = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
        return self.title

blogs/forms.py
from django import forms
from django.template.defaultfilters import slugify

from .models import Entry

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['title', 'text', 'public']
        #labels = {'text':''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}
    
    def clean(self):
        cleaned_data = super().clean()
        slug = slugify(cleaned_data.get('title'))
        if 'title' in self.changed_data:
            try:
                Entry.objects.get(slug=slug)
            except Entry.DoesNotExist:
                cleaned_data['slug'] = slug
                return cleaned_data
            else:
                self.add_error('title', 'This title is already in use.')

blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import EntryForm

def index(request):
    return render(request, 'blogs/index.html')

def about(request):
    return render(request, 'blogs/about.html')

def topics(request):
    '''Display all topics.'''
    return render(request, 'blogs/topics.html', {'topics': Topic.objects.order_by('name')})

def topic(request, slug):
    '''Display all public entries within a specific topic.'''
    topic = Topic.objects.get(slug=slug)
    entries = topic.entry_set.filter(public=True).order_by('-date_added')
    context = {
        'topic': topic,
        'entries': entries,
    }
    return render(request, 'blogs/topic.html', context)

def entry_detail(request, slug):
    entry = Entry.objects.get(slug=slug)
    if request.user.username != entry.owner.username and entry.public == False:
        raise Http404
    return render(request, 'blogs/entry_detail.html', {'entry': entry})

def user_entries(request, username):
    '''Display all entries (public and private) of an user for authenticated author user, public entries otherwise.'''
    if request.user.is_authenticated and request.user.username == username:
        filter_option = request.META.get('QUERY_STRING')
        # Check if there is any option
        if filter_option:
            filter_option = filter_option.split('=')
            # Check if the option is filter
            if filter_option[0] == 'filter':
                # Return public entries if filter == 'public', private entries if filter == 'private'
                if filter_option[1] == 'public':
                    filter_option = True
                elif filter_option[1] == 'private':
                    filter_option = False
                else:
                    filter_option = None
            else:
                filter_option = None
        else:                
            filter_option = None

        if filter_option is None:
            entries = Entry.objects.filter(owner__username=username).order_by('-date_added')
        else:
            entries = Entry.objects.filter(owner__username=username, public=filter_option).order_by('-date_added')
    else:
        entries = Entry.objects.filter(owner__username=username, public=True).order_by('-date_added')
    context = {
        'entries': entries,
        'author': username,
    }
    return render(request, 'blogs/user_entries.html', context)

@login_required
def new_entry(request, slug):
    '''Add a new entry.'''
    topic = Topic.objects.get(slug=slug)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.owner = request.user
            new_entry.slug = form.cleaned_data.get('slug')
            new_entry.save()
            return redirect('blogs:topic', slug=slug)
        
    # Display blank or invalid form.
    context = {
        'topic': topic,
        'form': form,
    }
    return render(request, 'blogs/new_entry.html', context)

@login_required
def edit_entry(request, slug):
    '''Edit an entry.'''
    entry = Entry.objects.get(slug=slug)
    topic = entry.topic
    if entry.owner != request.user:
        raise Http404
    if request.method != 'POST':
        # Pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            if 'title' in form.changed_data:
                edited_entry = form.save(commit=False)
                edited_entry.slug = form.cleaned_data.get('slug')
                edited_entry.save()
            else:
                form.save()
            return redirect('blogs:user_entries', username=entry.owner.username)
    
    context = {
        'entry': entry,
        'form': form,
    }
    return render(request, 'blogs/edit_entry.html', context)

@login_required
def delete_entry(request, slug):
    '''Delete an entry.'''
    entry = Entry.objects.get(slug=slug)
    topic = entry.topic
    if entry.owner != request.user:
        raise Http404
    if request.method != 'POST':
        return redirect('blogs:topic', slug=topic.slug)
    entry.delete()
    return redirect('blogs:user_entries', username=entry.owner.username)

blogs/templates/blogs/about.html
{% extends 'blogs/base.html' %}

{% block title %}
    <title>About</title>
{% endblock title %}

{% block header %}
    <h1>About</h1>
{% endblock header %}

{% block content %}
    <div class="fs-5">
        <p>This website is a personal project for praticing making a website using Python and Django, as well as Bootstrap for styling.</p>
        <p>
            This is a simple website with some basic features for user to work with blogs. You can choose a topic and read blogs
            within the topic, or access a specific user's page to see all their public blogs. If you want to make your own blogs,
            you can sign up for an account and start writing.
        </p>
        <p>
            With an account, you're able to create blogs of your own with a choice to make them public or private if you want other people
            to be able to see your blogs or not, as well as other features like editing, deleting and filtering.
        </p>
    </div>
{% endblock content %}

blogs/templates/blogs/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load django_bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
        <style>
            .hover-link:link {
                text-decoration: none;
            }
            .hover-link:hover {
                text-decoration: underline;
            }
        </style>
        {% block title %}{% endblock title %}
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-light sticky-top bg-white mb-4 py-3 border-bottom">
            <div class="container-fluid">
                <a class="navbar-brand text-primary fw-semibold" href="{% url 'blogs:index' %}">The Blog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link fw-semibold" href="{% url 'blogs:topics' %}">Topics</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link fw-semibold" href="{% url 'blogs:about' %}">About</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        {% if user.is_authenticated %}
                            <li class="nav-item mx-2">
                                <div class="dropdown">
                                    <button type="button" class="btn btn-outline-secondary" data-bs-toggle="dropdown" aria-expanded="false">
                                        {{ user.username }}
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-end">
                                        <a class="dropdown-item" href="{% url 'blogs:user_entries' user.username %}">My blogs</a>
                                        <hr class="dropdown-divider">
                                        <form class="dropdown-item px-0" action="{% url 'accounts:logout' %}" method="post">
                                            {% csrf_token %}
                                            <button type="submit" class="text-start border-0 bg-transparent px-3 w-100">Logout</button>
                                        </form>
                                    </div>
                                </div>
                            </li>
                        {% else %}
                            <li class="nav-item ms-2">
                                <a class="nav-link fw-semibold" href="{% url 'accounts:login' %}">Log in</a>
                            </li>
                            <li class="nav-item ms-2">
                                <a class="nav-link fw-semibold" href="{% url 'accounts:register' %}">Register</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <main style="max-width: 960px; margin: auto;">
            <div class="container">
                <div class="pb-2 mb-3 border-bottom">
                    {% block header %}{% endblock header %}
                </div>
                <div>
                    {% block content %}{% endblock content %}
                </div>
            </div>
        </main>
    </body>
</html>

blogs/templates/blogs/edit_entry.html
{% extends 'blogs/base.html' %}
{% load django_bootstrap5 %}

{% block title %}
    <title>Edit blog</title>
{% endblock title %}

{% block header %}
    <h1>Edit blog: {{ entry }}</h1>
{% endblock header %}

{% block content %}
    <form action="{% url 'blogs:edit_entry' entry.slug %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type='submit' content='Save' %}
    </form>
{% endblock content %}

blogs/templates/blogs/entry_detail.html
{% extends 'blogs/base.html' %}

{% block title %}
    <title>{{ entry.title }}</title>
{% endblock title %}

{% block header %}
    <h1>{{ entry.title }}</h1>
    <div class="d-flex">
        <span>By <a class="fw-semibold text-black" href="{% url 'blogs:user_entries' entry.owner.username %}">{{ entry.owner.username }}</a></span>
        <span class="ms-3"><i class="bi bi-calendar-date me-1"></i><small>{{ entry.date_added|date:'M d, Y H:i' }}</small></span>
        {% if entry.date_modified != entry.date_added %}
            <span class="ms-3"><small><span class="fw-semibold">Updated on</span> {{ entry.date_modified|date:'M d, Y H:i' }}</small></span>
        {% endif %}
    </div>
{% endblock header %}

{% block content %}
    {% if entry.public == False %}
        <div class="alert alert-warning" role="alert">This blog is in private mode. Only the author user can access this blog.</div>
    {% endif %}
    {{ entry.text|linebreaks }}
{% endblock content%}

blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}

{% block title %}
    <title>Homepage</title>
{% endblock title %}

{% block header %}
    <div class="p-3 mb-4 bg-light border rounded-3">
        <div class="container-fluid py-4">
            <h1 class="display-3">Sharing your stories.</h1>
            <p class="lead">Making your own blog and share it with everybody.</p>
            <a class="btn btn-primary" href="{% url 'accounts:register' %}">Register &raquo;</a>
        </div>
    </div>
{% endblock header %}

blogs/templates/blogs/new_entry.html
{% extends 'blogs/base.html' %}
{% load django_bootstrap5 %}

{% block title %}
    <title>Add new blog</title>
{% endblock title %}

{% block header %}
    <h1>Add new blog: {{ topic }}</h1>
{% endblock header %}

{% block content %}
    <form action="{% url 'blogs:new_entry' topic.slug %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type='submit' content='Add blog' %}
    </form>
{% endblock content %}

blogs/templates/blogs/topic.html
{% extends 'blogs/base.html' %}

{% block title %}
    <title>{{ topic }}</title>
{% endblock title %}

{% block header %}
    <div class="d-flex align-items-end">
        <h1>{{ topic }}</h1>
        <a href="{% url 'blogs:new_entry' topic.slug %}" class="btn btn-outline-primary btn-sm fw-semibold ms-auto">Add blog</a>
    </div>
{% endblock header %}

{% block content %}
    {% for entry in entries %}
        <article>
            <div class="card border-0 border-bottom mb-4">
                <div class="card-header border-0 bg-transparent">
                    By <a href="{% url 'blogs:user_entries' entry.owner.username %}" class="fw-semibold text-black">{{ entry.owner.username }}</a>
                    <i class="bi bi-clock ms-3 me-1"></i><small class="text-secondary" title="{{ entry.date_added|date:'M d, Y H:i' }}">{{ entry.date_added|timesince }} ago</small>
                </div>
                <div class="card-body py-2">
                    <h4 class="card-title">
                        <a href="{% url 'blogs:entry_detail' entry.slug %}" class="hover-link text-reset">{{ entry.title }}</a>                            
                    </h4>
                    <div class="card-text">{{ entry.text|truncatechars:300|linebreaks }}</div>
                </div>
                <div class="card-footer border-0 bg-transparent">
                    <a href="{% url 'blogs:topic' entry.topic.slug %}"
                    class="badge text-decoration-none text-black text-opacity-75 bg-secondary bg-opacity-10">{{ entry.topic }}</a>
                </div>
            </div>
        </article>
    {% empty %}
        <h3>No entries have been added.</h3>
    {% endfor %}
{% endblock content %}

blogs/templates/blogs/topics.html
{% extends 'blogs/base.html' %}

{% block title %}
    <title>Topics</title>
{% endblock title %}

{% block header %}
    <h1>Topics</h1>
{% endblock header %}

{% block content %}
    <ul class="list-group list-group-flush">
        {% for topic in topics %}
            <li class="list-group-item"><a href="{% url 'blogs:topic' topic.slug %}" class="text-black text-opacity-75 fs-4 text-decoration-none">{{ topic }}</a></li>
        {% empty %}
            <li class="list-group-item">No topics have been added.</li>
        {% endfor %}
    </ul>
{% endblock content %}

blogs/templates/blogs/user_entries.html
{% extends 'blogs/base.html' %}

{% block title %}
    <title>{{ author }}</title>
{% endblock title %}

{% block header %}
    <div class="d-flex align-items-end">
        <h1 class="text-break me-auto">@{{ author }}</h1>
        <span>{{ entries|length }} entr{{ entries|length|pluralize:'y,ies' }}</span>
        {% if user.username == author %}
        <div class="dropdown ms-3">
            <button type="button" class="btn btn-sm btn-outline-primary fw-semibold" data-bs-toggle="dropdown" aria-expanded="false">Filter</button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'blogs:user_entries' author %}?filter=public">Public</a></li>
                <li><a class="dropdown-item" href="{% url 'blogs:user_entries' author %}?filter=private">Private</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'blogs:user_entries' author %}">All</a></li>
            </ul>
            <a href="{% url 'blogs:user_entries' author %}"></a>
        </div>
        {% endif %}
    </div>
{% endblock header %}

{% block content %}
    {% for entry in entries %}
        <article>
            <div class="card border-0 border-bottom mb-4">
                <div class="card-header border-0 bg-transparent">
                    <div class="d-flex align-items-center">
                        <i class="bi bi-clock me-1"></i><small class="text-secondary" title="{{ entry.date_added|date:'M d, Y H:i' }}">{{ entry.date_added|timesince }} ago</small>
                            {% if user.username == author %}
                                <div class="btn-group btn-group-sm ms-auto">
                                    <a href="{% url 'blogs:edit_entry' entry.slug %}" class="btn btn-outline-secondary fw-semibold">Edit</a>
                                    <form class="btn btn-outline-secondary p-0" action="{% url 'blogs:delete_entry' entry.slug %}" method="post">
                                        {% csrf_token %}
                                        <button type="submit" class="fw-semibold text-reset border-0 bg-transparent px-2 py-1">Delete</button>
                                    </form>
                                </div>
                            {% endif %}
                    </div>
                </div>
                <div class="card-body py-2">
                    <h4 class="card-title">
                        <a href="{% url 'blogs:entry_detail' entry.slug %}" class="hover-link text-reset">{{ entry.title }}</a>
                    </h4>
                    <div class="card-text">{{ entry.text|truncatechars:300|linebreaks }}</div>
                </div>
                <div class="card-footer border-0 bg-transparent">
                    <a href="{% url 'blogs:topic' entry.topic.slug %}"
                    class="badge text-decoration-none text-black text-opacity-75 bg-secondary bg-opacity-10">{{ entry.topic }}</a>
                    {% if user.username == author %}
                        {% if entry.public == True %}
                            <span class="badge text-bg-primary">Public</span>
                        {% else %}
                            <span class="badge text-bg-warning">Private</span>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </article>
    {% empty %}
        <h2>No entries have been added.</h2>
    {% endfor %}
{% endblock content %}